# Generated by Django 3.0.3 on 2020-03-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='l_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='t_to',
            field=models.IntegerField(default=0),
        ),
    ]
