# Generated by Django 3.0.3 on 2020-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200303_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tile_num',
            field=models.IntegerField(default=0),
        ),
    ]
