# Generated by Django 3.0.3 on 2020-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_room_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='l_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='t_to',
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
