# Generated by Django 3.0.3 on 2020-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200305_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_location',
            field=models.CharField(default='Space', max_length=64),
        ),
    ]
